### ISSUE TITLE
We need examples of how Lifecycles work with global objects that "live" in Application scope

### ISSUE THREAD

**Issue by techyourchance** [googlecodelabs/android-lifecycles#12]
Hi guys,
I can't find an example of how to handle a situation when a callback needs to be dispatched from a global object that lives in Application scope.

Given the potential multiplicity of Lifecycles involved, is this possible at all?

I would like to refactor this code to use Lifecycles:

```
public class MyActivity extends Activity implements UserStateManagerListener {
 
    private UserStateManager mUserStateManager;
 
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ...
        mUserStateManager = ((MyApplication)getApplication()).getUserStateManager();
    }
 
    @Override
    protected void onStart() {
        super.onStart();
        mUserStateManager.registerListener(this);
    }
 
    @Override
    protected void onStop() {
        super.onStop();
        mUserStateManager.unregisterListener(this);
    }
 
    @Override
    public boolean onUserStateChanged(UserState userState) {
        ...
    }
}
```

**Comment by techyourchance** [comment]
Now I saw that LifecycleObserver's methods can receive the LifecycleOwner that generated the lifecycle event. Looks like the scenario of multiple observed lifecycles was considered.

I think that it can be possible to hold a mapping from LifecycleOwner to its respective callback, and use this information in lifecycle methods.

However, it is just my guess. Since it looks like this scenario was at least considered, it would be best to see how the authors intended this to work...

**Comment by JoseAlcerreca** [comment]
Stackoverflow might be a better forum. This one is for issues with the codelabs.
