### ISSUE TITLE
MyLocationListener in step_4 can cause memory leak

### ISSUE THREAD

**Issue by Zhuinden** [googlecodelabs/android-lifecycles#13]
The location listener callback is a non-static inner class of Activity and therefore registering it in the lifecycle listener can cause memory leak. 

It should be replaced with LiveData and ViewModel to show best practices, or needs a warning to specify that this is normally not how it should be done.

**Comment by JoseAlcerreca** [comment]
It's cleared in `removeLocationListener()`. Feel free to reopen if you still think it causes a memory leak.
