### ISSUE TITLE
Use of compareTo in android.arch.lifecycle.Lifecycle.State

### ISSUE THREAD

**Issue by paolop** [googlecodelabs/android-lifecycles#14]
This is not a bug it is more a suggestion and is referred to the usage of the Enum compareTo method (based on constants ordinals). As suggested by Joshua Bloch in Effective Java (Item 31 "Use instance fields instead of ordinals") I'd go for this approach given that it is less fragile and self-explaining.
Keep up the good work.

Paolo

**Comment by JoseAlcerreca** [comment]
Need more info
