### ISSUE TITLE
The observer should be bound to the Fragment's lifecycle in step 5

### ISSUE THREAD

**Issue by hjanos1** [googlecodelabs/android-lifecycles#18]
In step 5, the observer should be bound to the Fragment's lifecycle, not the Activity's.

This code should be changed to use the Fragment as LifecycleOwner (Fragment needs to extend LifecycleFragment):

```
mSeekBarViewModel.seekbarValue.observe(
    (LifecycleOwner) getActivity(),
    new Observer<Integer>() {
        @Override
        public void onChanged(@Nullable Integer value) {
            if (value != null) {
                mSeekBar.setProgress(value);
            }
        }
    });
```

**Comment by JoseAlcerreca** [comment]
Why? The idea is that the shared viewmodel has the same scope as the activity, not the fragment. In this particular case it wouldn't matter because the scope would be the same, but if a fragment is replaced then a new viewmodel would be created for it.
