### ISSUE TITLE
Documentation mistake - Lifecycle codelab - Step 3

### ISSUE THREAD

**Issue by ParaskP7** [googlecodelabs/android-lifecycles#19]
Within the "Update ChronoActivity" section and specifically on step (3.) it is being stated that:

"Notice that the log updates every second unless you navigate to another app. If your device supports multi-window mode, you may like to try using it."

However, the "multi-window" statement is misleading and kind of incorrect. When using "multi-window" and switching between apps while in that mode, the "onPause/onResume" will get triggered and not the "onStop", which in its turn will not cause the LiveData to stop observing (the timer will keep counting). LiveData stops observing for changes after an "onStop". 

So, the "onStop" will get triggered (and thus LiveData will stop observing for changes) when you navigate to another app, but not when you use multi-window mode.

**Comment by JoseAlcerreca** [comment]
Yeah, with multi-window mode onPause/onResume is triggered instead of onStop, so the timer doesn't stop counting. That's the behaviour we expect.
