### ISSUE TITLE
Though Activity_step5 is Launcher,how ChronoActivity1 is Launching First?

### ISSUE THREAD

**Issue by brajabasi** [googlecodelabs/android-lifecycles#20]
<activity android:name="com.example.android.lifecycles.step1.ChronoActivity1">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
            </intent-filter>
        </activity>
        <activity android:name="com.example.android.lifecycles.step2.ChronoActivity2">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
            </intent-filter>
        </activity>
        <activity android:name="com.example.android.lifecycles.step3.ChronoActivity3">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
            </intent-filter>
        </activity>
        <activity android:name="com.example.android.lifecycles.step3_solution.ChronoActivity3">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
            </intent-filter>
        </activity>
        <activity android:name="com.example.android.lifecycles.step4_solution.LocationActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
            </intent-filter>
        </activity>
        <activity android:name="com.example.android.lifecycles.step4.LocationActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
            </intent-filter>
        </activity>
        <activity android:name="com.example.android.lifecycles.step5.Activity_step5">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
            </intent-filter>
        </activity>
        <activity android:name="com.example.android.lifecycles.step5_solution.Activity_step5">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

**Comment by aagapow** [comment]
_Activity_step5_ is launched when you open the app from your phone. However in Android Studio you can set different _Launch Options_ for different **_Run Configurations_**. When you click on _Run_ > _Edit Configurations..._ you can see, that for _Step 1_ _ChronoActivity1_ is set as the launch activity.

If you want to start _Activity_step5_ from Android Studio you can for example run the _Step 5 - Sharing VMs solution_ configuration.
