### ISSUE TITLE
Step 2: LifecycleOwner is not needed to get a ViewModel

### ISSUE THREAD

**Issue by nil2l** [googlecodelabs/android-lifecycles#21]
You wrote:
> `this` refers to an instance of LifecycleOwner

You can change super class to just an Activity and it will work fine, like this:
`ChronoActivity2 extends AppCompatActivity`

Documentation for `ViewModelProviders.of` says about param `activity`

> an activity, in whose scope ViewModels should be retained

So LifecycleOwner is not needed to get a ViewModel.

**Comment by JoseAlcerreca** [comment]
An AppCompatActivity *is* a LifecycleOwner.
