### ISSUE TITLE
Codelab website is a bit out of date!

### ISSUE THREAD

**Issue by sadegh** [googlecodelabs/android-lifecycles#25]
In introduction part, it warn readers with this:

`Caution: The architecture component libraries are in an alpha state of development. The API may change before general availability, and you may encounter stability or performance issues. `

which is not valid anymore, since version 1.0 is stable.

https://codelabs.developers.google.com/codelabs/android-lifecycles/#0

**Comment by Zhuinden** [comment]
Only `Paging` library is still alpha at the moment.

I can barely wait for that one to be stable, it is amazing 😄

**Comment by JoseAlcerreca** [comment]
Fixed in #26
