### ISSUE TITLE
Step 2 requires some verification and instructions.

### ISSUE THREAD

**Issue by achie** [googlecodelabs/android-lifecycles#3]
Step 2 says open and examine how ChronoActivity2 uses ViewModel. And then it asks to run without giving instructions on what to change and expects a different output.

**Comment by JoseAlcerreca** [comment]
There's nothing to change in this step, it doesn't expect different output. Did you find a mismatch between what you see and what the codelab expects?

**Comment by achie** [comment]
Yeah, you are right. There is nothing to change in the repository itself. 

However, when I was following this while doing this at Google I/O, the steps described in the codelab were lacking in instructions on mentioning that this has to be opened by using a different configuration 
in Android studio. 
[https://codelabs.developers.google.com/codelabs/android-lifecycles/index.html?index=..%2F..%2Findex#2](https://codelabs.developers.google.com/codelabs/android-lifecycles/index.html?index=..%2F..%2Findex#2)

So it would be helpful to call attention different configurations that have to be set in the IDE from the codelab instructions.

**Comment by JoseAlcerreca** [comment]
Right, noted, thanks!

**Comment by serguei-eb** [comment]
Indeed, in the **Try it out** section should it would be good to mention to run the app Using "Step 2 - View Model" configuration

**Comment by JoseAlcerreca** [comment]
Fixed in #26
