### ISSUE TITLE
Step3 error

### ISSUE THREAD

**Issue by ghost** [googlecodelabs/android-lifecycles#31]
java.lang.IllegalStateException: Cannot invoke setValue on a background thread

 public LiveDataTimerViewModel() {
        mInitialTime = SystemClock.elapsedRealtime();
        Timer timer = new Timer();

        // Update the elapsed time every second.
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                 final long newValue = (SystemClock.elapsedRealtime() - mInitialTime) / 1000;

                // setValue() cannot be called from a background thread so post to main thread.
                //TODO post the new value with LiveData.postValue()
 mElapsedTime.setValue(newValue);
            }
        }, ONE_SECOND, ONE_SECOND);
        Long newValue = null;
        mElapsedTime.setValue(newValue);
    }

**Comment by jaredrummler** [comment]
You need to use [`postValue`](https://developer.android.com/reference/android/arch/lifecycle/LiveData.html#postValue(T)) instead of `setValue` because it is running in a background thread. The codelab instructs you to use `setValue` and should be updated.

**Comment by steele232** [comment]
I have found this too.

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback! Completely correct - code comment was updated and now updating the text.
