### ISSUE TITLE
Unable to build the project 

### ISSUE THREAD

**Issue by Tej333** [googlecodelabs/android-lifecycles#33]
![image](https://user-images.githubusercontent.com/36147802/35790286-6687186c-0a67-11e8-8acd-f902240b3344.png)

and the corresponding SDK version is not available.
![image](https://user-images.githubusercontent.com/36147802/35790299-95f48742-0a67-11e8-8d82-cd49f919393c.png)

 What should be done?

**Comment by pedrovarela86** [comment]
First check for updates of Android Studio. 

You don't have Android 8.1 which is version 27. 

Go to Android Studio menu, and Check for Updates.

**Comment by Tej333** [comment]
Thanks for the quick response !

**Comment by Tej333** [comment]
[image: Inline image 1]
even after
[image: Inline image 2]

**Comment by jabubake** [comment]
@Tej333 : we have recently updated the project. Please try it with Android Studio 3.2.1 (latest stable) and let us know if you still run into any issues.
