### ISSUE TITLE
Error when opening from Android Studio 3.1

### ISSUE THREAD

**Issue by AndreSand** [googlecodelabs/android-lifecycles#34]
Can Google engineer update the project to use the latest gradle 3.1.0 and AS 3.1?
```Configuration 'compile' is obsolete and has been replaced with 'implementation'.
It will be removed at the end of 2018


Configuration 'androidTestApi' is obsolete and has been replaced with 'androidTestImplementation'.
It will be removed at the end of 2018


Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018


Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018


Configuration 'androidTestCompile' is obsolete and has been replaced with 'androidTestImplementation'.
It will be removed at the end of 2018
```
This example is broken :( 
you have to update some gradle settings to get it to work..

**Comment by ben-8409** [comment]
The errors above can be ignored and the project still builds. However, I had additional errors with the build config. I made some changes that did the trick for me:
https://github.com/ben-8409/android-lifecycles/tree/update-dependencies-and-build-gradle

**Comment by jabubake** [comment]
@AndreSand @ben-8409  : We recently upgraded the project to 3.2.1 (latest stable).  Please let us know if you run into any more issues.
