### ISSUE TITLE
Android 3.1.2

### ISSUE THREAD

**Issue by Julie-Menezes** [googlecodelabs/android-lifecycles#36]
Doesn't work. After updates it auto selects a virtual device. The AVD then complains that VTx is disabled in BIOS even though VTd is enabled in BIOS! I was trying to run a Codelab Project. https://codelabs.developers.google.com/codelabs/android-lifecycles/#1 Note: My other projects run fine on a real device.

**Comment by jabubake** [comment]
@Julie-Menezes : we have recently updated the project. Please try it with Android Studio 3.2.1 (latest stable) and let us know if you still run into any issues.
