### ISSUE TITLE
Use custom ViewModel constructor

### ISSUE THREAD

**Issue by daimonkor** [googlecodelabs/android-lifecycles#4]
Please write easy example, where ViewModel will use custom constructor with ViewDataBinding class. How init/restore its ViewModel? 
I see only Class type
`ViewModelProviders.of(this).get(CustomResultViewModel.class);`
Thanks for help.

**Comment by JoseAlcerreca** [comment]
https://github.com/googlesamples/android-architecture-components/blob/master/BasicSample/app/src/main/java/com/example/android/persistence/ProductFragment.java#L71

**Comment by daimonkor** [comment]
Thanks.

**Comment by caleb-allen** [comment]
That link is broken for me. I believe this is the correct link:

https://github.com/googlesamples/android-architecture-components/blob/master/BasicSample/app/src/main/java/com/example/android/persistence/ui/ProductFragment.java
