### ISSUE TITLE
Default activity is not set as expected for Step 1

### ISSUE THREAD

**Issue by jasongiss** [googlecodelabs/android-lifecycles#41]
When following the codelab, and downloading the source, when you run the application you get an activity containing 2 sliders, rather than the **ChronoActivity1** activity described.

This is because the AndroidManifest.xml sets the last activity (for step 5) to be default by adding:

`<category android:name="android.intent.category.LAUNCHER" />`

Presumably this should instead be set on the Step 1 activity?

**Comment by hahn** [comment]
maybe you must revert `runConfiguration` folder. It's work for me
<img width="340" alt="screen shot 2018-10-05 at 14 05 02" src="https://user-images.githubusercontent.com/315048/46520867-c41b0980-c8a7-11e8-8012-c53bc5ae8f8a.png">

**Comment by flintt** [comment]
just right click "ChromeActivity1" and select run.
![image](https://user-images.githubusercontent.com/3394691/47072115-f58cc100-d227-11e8-8f7b-e45782d58ef0.png)
![image](https://user-images.githubusercontent.com/3394691/47072151-0806fa80-d228-11e8-8d71-ad6154f4417a.png)

**Comment by malhobayyeb** [comment]
The codelab says 

> Run the Step 1 run configuration on a device or emulator.

However, the project is not configured as per the codelab instructions.

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback! 

As suggested, I'm setting this to open step 1 as the default and updating the screenshots in the codelab to make it more clear that you need to run the commands at the start of the codelab: https://codelabs.developers.google.com/codelabs/android-lifecycles/#1
