### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by varunam** [googlecodelabs/android-lifecycles#43]
Build project fails with below error

Could not find runtime.aar (android.arch.lifecycle:runtime:1.0.3).
Searched in the following locations:
    https://jcenter.bintray.com/android/arch/lifecycle/runtime/1.0.3/runtime-1.0.3.aar

**Comment by varunam** [comment]
Surprisingly, changing order of repositories under buildscripts and allprojects with google() at the first place solved this issue. 

I referred to [this](https://stackoverflow.com/a/52127519/6217764) answer on SOF. 

If anybody can explain how did this solve the problem, it would be really helpful.

**Comment by jabubake** [comment]
@varunam  : we have recently updated the project. Please try it with Android Studio 3.2.1 (latest stable) and let us know if you still run into any issues.
