### ISSUE TITLE
update the codelab

### ISSUE THREAD

**Issue by moehawamdeh** [googlecodelabs/android-lifecycles#45]
The codelab at
https://codelabs.developers.google.com/codelabs/android-lifecycles/
uses deprecated classes, It should be mentioned that AppcompatActivity replaces LifecycleActivity.

**Comment by tompad2** [comment]
+1

**Comment by jabubake** [comment]
@moehawamdeh  @tompad2 : we have recently updated the project. Please try it with Android Studio 3.2.1 (latest stable) and let us know if you still run into any issues.

**Comment by Karthick-Ramanathan** [comment]
U have changed in project but codelabs [https://codelabs.developers.google.com/codelabs/android-lifecycles/#3](url) still shows LifecycleActivity
