### ISSUE TITLE
Lifecycle Observer is not removed in step_4

### ISSUE THREAD

**Issue by Zhuinden** [googlecodelabs/android-lifecycles#5]
[Here](https://github.com/googlecodelabs/android-lifecycles/blob/master/app/src/main/java/com/example/android/lifecycles/step4_solution/BoundLocationManager.java#L45), there is `addObserver()` call, but there is no `removeObserver()` call for onDestroy. Is this intentional?

**Comment by JoseAlcerreca** [comment]
Yes, that's the whole point of the new lifecycle-aware components, no need to unsubscribe/remove observers.

**Comment by Zhuinden** [comment]
Cool! Thanks :D

**Comment by AndroidDeveloperLB** [comment]
Can you please update the docs about it?
As a precaution, I always remove the observer when not needed (even asked about it [here](https://stackoverflow.com/q/51872113/878126)), even if I use it just for onDestroy event.
It's especially true for ON_DESTROY , that we don't need to call removeObserver for it, so maybe add a note there:

https://developer.android.com/reference/android/arch/lifecycle/Lifecycle.Event#ON_DESTROY

?

**Comment by trevorhackman** [comment]
In the event that onDestroy which is not guaranteed to be called, is not called, does the observer ever get removed?
