### ISSUE TITLE
Codelab web pages refer to deprecated classes

### ISSUE THREAD

**Issue by steve-madsen-treatwell** [googlecodelabs/android-lifecycles#57]
The codelab documentation (not the github code, but the web page instructions) refer to classes deprecated in Jan 2018:
`LifecycleActivity`
`LifecycleFragment`
(Offending page: https://codelabs.developers.google.com/codelabs/android-lifecycles/#3)

This was raised previously (https://github.com/googlecodelabs/android-lifecycles/issues/45) but was closed without fixing the problem

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback! You're 100% right, fixing this now.
