### ISSUE TITLE
LocationActivity crashes on Configuration change when App ask for location permission.

### ISSUE THREAD

**Issue by sijangurung** [googlecodelabs/android-lifecycles#58]
On Step-4 :
As mentioned above, When the configuration is changed when App is asking for Location Permission, the onRequestPermissionsResult() method will be called again where it will find grantResults as empty array, so the grantResult[0] will result in ArrayOutOfBoundIndex Exception.
Fix:

 @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions,
                                           @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        if (requestCode == REQUEST_LOCATION_PERMISSION_CODE && grantResults.length > 0) {
            ... < all code remaining same >
        }
    } 
- Checking if the grantResult is empty or not.

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback! Added the check to protect against the exception. Thank you!
