### ISSUE TITLE
Cancel Timer

### ISSUE THREAD

**Issue by aidanmack** [googlecodelabs/android-lifecycles#59]
Hello,
I was originally just googling for examples of a Timer in a Viewmodel and came across this repo

With regards to the timer used here...
https://github.com/googlecodelabs/android-lifecycles/blob/17c5b6fcec2eb2de3f943557bcca3b209d110671/app/src/main/java/com/example/android/lifecycles/step3_solution/LiveDataTimerViewModel.java#L40

Dont we still need to cancel that in the viewmodel?
Something like....

override fun onCleared() {
        super.onCleared()
        timer.cancel()
    }

**Comment by GorkemKarayel** [comment]
When we work with the Activity , it may make sense to cancel onClear (). How do we cancel when we work with the fragment ?

**Comment by aidanmack** [comment]
@GorkemKarayel  ... I might of miss understood your question but...

 hmmm I've never come across any reason to cancel an `onCleared()` in a viewmodel. were overiding the onCleared ... So even if you dont overide.. Its still going to happen.

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback! Just submitted a fix!
