### ISSUE TITLE
Step2 - run correctly  without activity extending from LifecycleActivity

### ISSUE THREAD

**Issue by ciprig** [googlecodelabs/android-lifecycles#6]
Step 2 could be simplify as for proper implementation only ViewModel notion is required without LifecycleActivity.

**Comment by JoseAlcerreca** [comment]
To be clear: ChronoActivity2 can be an Activity instead of a LifecycleActivity.

**Comment by JoseAlcerreca** [comment]
No, it can't, in ChronoActivity2, a LifecycleOwner is required:

```
        ChronometerViewModel chronometerViewModel
                = ViewModelProviders.of(this).get(ChronometerViewModel.class);
```
