### ISSUE TITLE
The EVENT class needs to be refactored to Event

### ISSUE THREAD

**Issue by mohitajwani** [googlecodelabs/android-lifecycles#61]
The `EVENT` Enum needs to be refactored to `Event` as the `Lifecycle` class does not have `EVENT`, instead it is `Event` as an Enum.

https://codelabs.developers.google.com/codelabs/android-lifecycles/#4

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback! You're correct and I'm updating the codelab text now. Thank you!
