### ISSUE TITLE
Step3 : LifecycleRegistryOwner was deplicated

### ISSUE THREAD

**Issue by hiyadana** [googlecodelabs/android-lifecycles#64]
LifecycleRegistryOwner is mentioned in the Step3 description.
But LifecycleRegistryOwner was deprecated in API level 1.1.0.

**Comment by hakimrie** [comment]
as per this SO https://stackoverflow.com/questions/55303033/androidx-appcompat-app-appcompatactivity-doesnt-implement-lifecycleowner 
you must update app compat library version

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback! You are indeed correct, LifecycleRegistryOwner is deprecated - ComponentActivity and Fragment now simply implement LifecycleOwner. The language of the codelab is being updated to reflect this.
