### ISSUE TITLE
LiveDataTimerViewModel Example. No need for canceling timer?

### ISSUE THREAD

**Issue by krial057** [googlecodelabs/android-lifecycles#65]
I have a question concerning the `LiveDataTimerViewModel ` example. Wouldn't it make sense to call the  `timer.cancel()` method in the ViewModel's `onCleared()` method? I had very similar code as in the example and LeakCanary gave me a leak notfication. Adding the `timer.cancel ()` fixed the leak.
Kind regards,
Alain

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback! Just submitted a fix!
