### ISSUE TITLE
Steps  6 StateLifecyle

### ISSUE THREAD

**Issue by zawawimanja** [googlecodelabs/android-lifecycles#69]
1. I try to kill the apps then go back into the apps but the data is not saved .Why?

2. I tried to make new activity by intent it. I ln new activity I implement the same code as statelifecyle. But why when I backpressed and try to enter back the newactivity the data is not saved ?

3. I think need to use Room for persisted of the data.

**Comment by CJEEP** [comment]
> 1. I try to kill the apps then go back into the apps but the data is not saved .Why?
> 2. I tried to make new activity by intent it. I ln new activity I implement the same code as statelifecyle. But why when I backpressed and try to enter back the newactivity the data is not saved ?
> 3. I think need to use Room for persisted of the data.

This function is not for local persistent storage, but for situations of abnormal life cycle, such as when working in the background, the memory is not enough, the page may be destroyed and data loss，maybe you can:
1.Press the home button and use adb command to kill the process : 
command ：
(1) adb shell am kill com.example.android.codelabs.lifecycle , "com.example.android.codelab
s.lifecycle" change to your package name;

2.Back in the foreground, you will see the saved data. If SavedStateHandle is not used, there is no data.

**Comment by zawawimanja** [comment]
Actually I had did the process using adb terminal like the steps. But the
data still not persist.
