### ISSUE TITLE
Relevant name for startDate field

### ISSUE THREAD

**Issue by andreilisun** [googlecodelabs/android-lifecycles#8]
Looks like `startDate`  field name [here](https://github.com/googlecodelabs/android-lifecycles/blob/5684e15cccd859459acdb9cfa82f8bdc98871941/app/src/main/java/com/example/android/lifecycles/step2/ChronometerViewModel.java#L29) is irrelevant. `startTime` or  [`mInitialTime`](https://github.com/googlecodelabs/android-lifecycles/blob/5684e15cccd859459acdb9cfa82f8bdc98871941/app/src/main/java/com/example/android/lifecycles/step3/LiveDataTimerViewModel.java#L39) would make sense.

**Comment by JoseAlcerreca** [comment]
Done
